package com.example.jokingApp.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.jokingApp.db.PersonEntity;
import com.example.jokingApp.db.JokeEntity;

import com.example.jokingApp.db.PersonEntityDao;
import com.example.jokingApp.db.JokeEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personEntityDaoConfig;
    private final DaoConfig jokeEntityDaoConfig;

    private final PersonEntityDao personEntityDao;
    private final JokeEntityDao jokeEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personEntityDaoConfig = daoConfigMap.get(PersonEntityDao.class).clone();
        personEntityDaoConfig.initIdentityScope(type);

        jokeEntityDaoConfig = daoConfigMap.get(JokeEntityDao.class).clone();
        jokeEntityDaoConfig.initIdentityScope(type);

        personEntityDao = new PersonEntityDao(personEntityDaoConfig, this);
        jokeEntityDao = new JokeEntityDao(jokeEntityDaoConfig, this);

        registerDao(PersonEntity.class, personEntityDao);
        registerDao(JokeEntity.class, jokeEntityDao);
    }
    
    public void clear() {
        personEntityDaoConfig.getIdentityScope().clear();
        jokeEntityDaoConfig.getIdentityScope().clear();
    }

    public PersonEntityDao getPersonEntityDao() {
        return personEntityDao;
    }

    public JokeEntityDao getJokeEntityDao() {
        return jokeEntityDao;
    }

}
