package com.example.jokingApp.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "JOKE_ENTITY".
 */
public class JokeEntity {

    private String des;
    private String imageurl;
    private String name;
    private String url;
    private String id;

    public JokeEntity() {
    }

    public JokeEntity(String des, String imageurl, String name, String url, String id) {
        this.des = des;
        this.imageurl = imageurl;
        this.name = name;
        this.url = url;
        this.id = id;
    }

    public String getDes() {
        return des;
    }

    public void setDes(String des) {
        this.des = des;
    }

    public String getImageurl() {
        return imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

}
