package com.example.jokingApp.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSON_ENTITY".
 */
public class PersonEntity {

    private Long id;
    private String name;
    private Integer age;
    private String sex;
    private String url;

    public PersonEntity() {
    }

    public PersonEntity(Long id) {
        this.id = id;
    }

    public PersonEntity(Long id, String name, Integer age, String sex, String url) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.sex = sex;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
